"""PDF security report generation.

Builds the downloadable PDF report with ReportLab (a pure-Python library with
no system-level dependencies, so it works in the slim runtime container).
Every figure in the document comes from the live database aggregates in
:class:`app.schemas.report.ReportSummary` — the report contains no static or
sample content.
"""

from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.schemas.report import ReportSummary

PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN = 18 * mm
CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN

INK = colors.HexColor("#0f172a")
ACCENT = colors.HexColor("#0ea5e9")
GRID = colors.HexColor("#e2e8f0")
GREY = colors.HexColor("#64748b")

TITLE_STYLE = ParagraphStyle(
    "ReportTitle",
    fontName="Helvetica-Bold",
    fontSize=20,
    leading=24,
    textColor=colors.white,
    alignment=TA_CENTER,
)
SUBTITLE_STYLE = ParagraphStyle(
    "ReportSubtitle",
    fontName="Helvetica",
    fontSize=10,
    leading=14,
    textColor=colors.HexColor("#cbd5e1"),
    alignment=TA_CENTER,
)
H2_STYLE = ParagraphStyle(
    "SectionHeading",
    fontName="Helvetica-Bold",
    fontSize=13,
    leading=16,
    textColor=INK,
    spaceBefore=10,
    spaceAfter=4,
)
BODY_STYLE = ParagraphStyle(
    "Body",
    fontName="Helvetica",
    fontSize=9.5,
    leading=13,
    textColor=INK,
)
META_STYLE = ParagraphStyle(
    "Meta",
    parent=BODY_STYLE,
    textColor=GREY,
    fontSize=9,
)
INLINE_STYLE = ParagraphStyle(
    "InlineCell",
    fontName="Helvetica",
    fontSize=8.5,
    leading=11,
    textColor=INK,
)
INLINE_BOLD_STYLE = ParagraphStyle(
    "InlineCellBold",
    parent=INLINE_STYLE,
    fontName="Helvetica-Bold",
)


def _fmt(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _value_table(headers: list[str], rows: list[list[str]]) -> Table:
    """A two-column style label/value table plus optional extra columns."""
    data = [headers] + rows
    table = Table(data, colWidths=[CONTENT_WIDTH * 0.42, CONTENT_WIDTH * 0.58], repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), INK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("GRID", (0, 0), (-1, -1), 0.4, GRID),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]
    table.setStyle(TableStyle(style))
    return table


def _bullet_table(title: str, rows: list[tuple[str, str]]) -> Table | Paragraph:
    data = [[Paragraph(title, INLINE_BOLD_STYLE), ""]] + [
        [Paragraph(name, INLINE_STYLE), Paragraph(str(count), INLINE_STYLE)]
        for name, count in rows
    ]
    table = Table(data, colWidths=[CONTENT_WIDTH * 0.75, CONTENT_WIDTH * 0.25])
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e0f2fe")),
        ("SPAN", (0, 0), (1, 0)),
        ("GRID", (0, 0), (-1, -1), 0.4, GRID),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
    ]
    table.setStyle(TableStyle(style))
    return table


def _footer(canvas, doc):
    """Page footer: source label left, page number right, rule above."""
    canvas.saveState()
    canvas.setStrokeColor(GRID)
    canvas.setLineWidth(0.4)
    canvas.line(MARGIN, 12 * mm, PAGE_WIDTH - MARGIN, 12 * mm)
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(GREY)
    canvas.drawString(MARGIN, 8 * mm, "Generated by SentinelX — sourced from live database aggregates.")
    canvas.drawRightString(PAGE_WIDTH - MARGIN, 8 * mm, f"Page {doc.page}")
    canvas.restoreState()


def generate_report_pdf(summary: ReportSummary, app_name: str, generated_at: datetime) -> bytes:
    """Render ``summary`` into a single-document PDF and return the bytes."""
    from io import BytesIO

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=20 * mm,
        title=f"{app_name} Security Report",
        author=app_name,
    )

    story = []

    # Title banner.
    banner = Table(
        [[Paragraph(f"{app_name} — Security Report", TITLE_STYLE),
          Paragraph(f"Security event summary for the last {summary.days} days", SUBTITLE_STYLE)]],
        colWidths=[CONTENT_WIDTH],
    )
    banner.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), INK),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 14),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
            ]
        )
    )
    story.append(banner)

    story.append(Spacer(1, 10))
    story.append(
        Paragraph(
            f"<b>Report period:</b> {_fmt(summary.range_start)} — {_fmt(summary.range_end)}"
            f"&nbsp;&nbsp;·&nbsp;&nbsp;<b>Generated:</b> {_fmt(generated_at)}",
            META_STYLE,
        )
    )
    story.append(Spacer(1, 4))

    # Executive summary.
    story.append(Paragraph("Executive summary", H2_STYLE))
    summary_rows = [
        ("Total security events", str(summary.total_events)),
        ("Total alerts raised", str(summary.total_alerts)),
    ]
    if summary.avg_resolution_minutes is not None:
        summary_rows.append(("Average resolution time (minutes)", str(summary.avg_resolution_minutes)))
    story.append(_value_table(["Metric", "Value"], summary_rows))

    # Severity breakdown.
    story.append(Paragraph("Alerts by severity", H2_STYLE))
    severity = {item.severity: item.count for item in summary.by_severity}
    sev_plots = {
        "Critical": severity.get("CRITICAL", 0),
        "High": severity.get("HIGH", 0),
        "Medium": severity.get("MEDIUM", 0),
        "Low": severity.get("LOW", 0),
    }
    story.append(
        _value_table(["Severity", "Alerts"], [[k, str(v)] for k, v in sev_plots.items()])
    )

    # Status breakdown.
    story.append(Paragraph("Alerts by status", H2_STYLE))
    status = {item.status: item.count for item in summary.by_status}
    status_plots = {
        "Open": status.get("OPEN", 0),
        "Investigating": status.get("INVESTIGATING", 0),
        "Resolved": status.get("RESOLVED", 0),
    }
    story.append(
        _value_table(["Status", "Alerts"], [[k, str(v)] for k, v in status_plots.items()])
    )

    # Top alert types (most triggered detection rules).
    story.append(Paragraph("Most triggered detection rules", H2_STYLE))
    if summary.top_alert_types:
        story.append(
            _bullet_table(
                "Detection rule",
                [(item.alert_type, item.count) for item in summary.top_alert_types],
            )
        )
    else:
        story.append(Paragraph("No alerts were raised in the period.", BODY_STYLE))

    # Daily activity summary (security event/alert summary).
    story.append(Paragraph("Daily security event / alert summary", H2_STYLE))
    daily_events = {point.day: point.events for point in summary.by_day_events}
    daily_rows = [
        [point.day, str(daily_events.get(point.day, 0)), str(point.alerts)]
        for point in summary.by_day_alerts
    ]
    if daily_rows:
        table = Table(
            [["Day", "Events", "Alerts"]] + daily_rows,
            colWidths=[CONTENT_WIDTH * 0.4, CONTENT_WIDTH * 0.3, CONTENT_WIDTH * 0.3],
            repeatRows=1,
        )
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), INK),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 9),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                    ("GRID", (0, 0), (-1, -1), 0.4, GRID),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("ALIGN", (1, 0), (-1, -1), "CENTER"),
                ]
            )
        )
        story.append(table)
    else:
        story.append(Paragraph("No activity recorded in the period.", BODY_STYLE))

    # Top source IPs and event types side by side-ish (stacked).
    story.append(Paragraph("Top source IPs", H2_STYLE))
    if summary.top_source_ips:
        story.append(
            _bullet_table("Source IP", [(item.source_ip, item.count) for item in summary.top_source_ips])
        )
    else:
        story.append(Paragraph("No source IPs recorded in the period.", BODY_STYLE))

    story.append(Paragraph("Top event types", H2_STYLE))
    if summary.top_event_types:
        story.append(
            _bullet_table(
                "Event type", [(item.event_type, item.count) for item in summary.top_event_types]
            )
        )
    else:
        story.append(Paragraph("No events recorded in the period.", BODY_STYLE))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()